print("Loading default plugins and configurations...")

require("plugins.theme")
require("plugins.noice")
require("plugins.notify")
require("plugins.lualine")
require("plugins.bufferline")
require("plugins.alpha")

require("plugins.gitsigns")
require("plugins.telescope")
require("plugins.which-key")
require("plugins.neo-tree")
require("plugins.oil")
require("plugins.trouble")
require("plugins.todo-comments")
require("plugins.mini-pairs")
require("plugins.ts-context-commentstring")
require("plugins.persistence")
